kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: verification-test-service-account
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: bvt-cluster-claim-sa
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view